### ISSUE TITLE
Undefined symbol while importing 'torch-sparse'

### ISSUE THREAD

**Issue by matteotolloso** [rusty1s/pytorch_sparse#395]
Hello everyone, I have the following issue using torch-sparse:

CUDA Version: 12.4 
Architecture: aarch64
OS: Ubuntu 22.04.5 LTS

This is what I did:

`conda create -n test python=3.11`
`conda activate test`
`pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu124`
`pip install torch_geometric`
`pip install torch-sparse -f https://data.pyg.org/whl/torch-2.5.0+cu124.html`

When I do

`pip freeze | grep torch`

I get:
`
torch==2.5.1
torch-geometric==2.6.1
torch_sparse==0.6.18
torchaudio==2.5.1
torchvision==0.20.1`

The problem is:

`import torch_geometric`

`
/vast/user/miniconda3/envs/test/lib/python3.11/site-packages/torch_geometric/typing.py:124: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /vast/user/miniconda3/envs/test/lib/python3.11/site-packages/torch_sparse/_spmm_cpu.so: undefined symbol: _ZN5torch8autograd12VariableInfoC1ERKN2at6TensorEb`

Thanks for your help!

**Comment by rahit** [comment]
I can confirm the same issue with the following environment:

```pixi.toml
[workspace]
name = "test-env"
version = "0.1.0"
channels = ["nvidia", "pytorch", "conda-forge"]
platforms = ["linux-64"]

[system-requirements]
cuda = "12.1"

[tasks]
test = { cmd = "python test_env.py" }

[dependencies]
python = "3.10.*"
cuda-version = "12.1.*"
pytorch-cuda = {version = "12.1.*", channel = "pytorch"}

[pypi-dependencies]
torch = { version = ">=2.1.0", index = "https://download.pytorch.org/whl/cu121" }
torch-geometric = ">=2.6.1, <3"
pyg_lib = { url = "https://data.pyg.org/whl/torch-2.1.0%2Bcu121/pyg_lib-0.3.1%2Bpt21cu121-cp310-cp310-linux_x86_64.whl" }
torch_cluster = { url = "https://data.pyg.org/whl/torch-2.1.0%2Bcu121/torch_cluster-1.6.3%2Bpt21cu121-cp310-cp310-linux_x86_64.whl" }
torch_scatter = { url = "https://data.pyg.org/whl/torch-2.1.0%2Bcu121/torch_scatter-2.1.2%2Bpt21cu121-cp310-cp310-linux_x86_64.whl" }
torch_sparse = { url = "https://data.pyg.org/whl/torch-2.1.0%2Bcu121/torch_sparse-0.6.18%2Bpt21cu121-cp310-cp310-linux_x86_64.whl" }
torch_spline_conv = { url = "https://data.pyg.org/whl/torch-2.1.0%2Bcu121/torch_spline_conv-1.2.2%2Bpt21cu121-cp310-cp310-linux_x86_64.whl" }


```
_Versions are pinned because of issue #377 . I followed https://github.com/rusty1s/pytorch_sparse/issues/377#issuecomment-2175624203 solution._


test_env.py
```python

#! /usr/bin/env python 
# -------------------------------------------------------
import os
import sys
import socket
import torch
# -------------------------------------------------------
print("Defining torch tensors:")
x = torch.Tensor(5, 3)
print(x)
y = torch.rand(5, 3)
print(y)

# -------------------------------------------------------
# let us run the following only if CUDA is available
if torch.cuda.is_available():
    print("CUDA is available.")
    x = x.cuda()
    y = y.cuda()
    print(x + y)
else:
    print("CUDA is NOT available.")
print(f"CUDA version: {torch.version.cuda}")

print("-------------------------------------------------------")

dev = os.environ['CUDA_VISIBLE_DEVICES']

host = socket.gethostname()
tdev = torch.cuda.current_device()
tavail = torch.cuda.is_available()
tcount = torch.cuda.device_count()
tname = torch.cuda.get_device_name()

print("Host: %s\nENV Devices: %s\nCudaDev: %s\nCUDA is available: %s\nDevice count: %d\nDevice: %s" % \
        (host, dev, tdev, tavail, tcount, tname))

print(os.popen("/usr/bin/nvidia-smi -L").read().strip())
print(os.popen("env | grep CUDA").read().strip())
print("")
# -------------------------------------------------------


try:
    from torch_sparse import SparseTensor

    # Create test data
    row = torch.tensor([0, 1, 1, 2])
    col = torch.tensor([1, 0, 2, 1])
    value = torch.tensor([1.0, 2.0, 3.0, 4.0])

    # Create a SparseTensor
    sparse_tensor = SparseTensor(
        row=row,
        col=col,
        value=value,
        sparse_sizes=(3, 3)  # Matrix dimensions
    )

    print("SparseTensor created successfully!")
    print("\nSparseTensor properties:")
    print(f"Shape: {sparse_tensor.sizes()}")
    print(f"Number of non-zero elements: {sparse_tensor.nnz()}")
    print(f"\nDense representation:\n{sparse_tensor.to_dense()}")

    # Test basic operations
    print("\nTesting basic operations:")
    # Test matrix multiplication
    x = torch.randn(3, 2)
    out = sparse_tensor @ x
    print(f"\nMatrix multiplication result shape: {out.shape}")

    # Test device movement
    if torch.cuda.is_available():
        print("\nMoving to GPU...")
        sparse_tensor_gpu = sparse_tensor.cuda()
        print("Successfully moved to GPU!")
except ImportError as e:
    print(f"torch_sparse not found: {e}")



```


```bash
$ pixi run setup
Pixi task (setup): python test_env.py
Defining torch tensors:
tensor([[ 0.0000e+00,  0.0000e+00,  5.0858e-27],
        [ 4.5678e-41,  1.2472e-43,  1.8217e-44],
        [ 4.7224e-43,  0.0000e+00, -1.1160e+06],
        [ 4.5678e-41,  4.1125e-34,  3.0942e-41],
        [ 4.0940e-27,  4.5678e-41,  1.2472e-43]])
tensor([[0.6349, 0.0914, 0.6659],
        [0.0828, 0.3512, 0.2486],
        [0.3818, 0.7742, 0.4180],
        [0.9984, 0.7779, 0.3786],
        [0.8330, 0.2181, 0.4077]])
CUDA is available.
tensor([[ 6.3487e-01,  9.1426e-02,  6.6592e-01],
        [ 8.2815e-02,  3.5117e-01,  2.4863e-01],
        [ 3.8178e-01,  7.7424e-01, -1.1160e+06],
        [ 9.9838e-01,  7.7785e-01,  3.7855e-01],
        [ 8.3302e-01,  2.1808e-01,  4.0775e-01]], device='cuda:0')
CUDA version: 12.1
-------------------------------------------------------
Host: mmg1
ENV Devices: 0
CudaDev: 0
CUDA is available: True
Device count: 1
Device: NVIDIA A100-PCIE-40GB
GPU 0: NVIDIA A100-PCIE-40GB (UUID: GPU-96b9a6b1-52d0-c857-1f68-4959efe6c065)
CUDA_MODULE_LOADING=LAZY
CONDA_OVERRIDE_CUDA=12.1
CUDA_OVERRIDE_VERSION=12.1
CUDA_VISIBLE_DEVICES=0

Traceback (most recent call last):
  File "/work/mtgraovac_lab/rahit/test/test_env.py", line 45, in <module>
    from torch_sparse import SparseTensor
  File "/work/mtgraovac_lab/rahit/test/.pixi/envs/default/lib/python3.10/site-packages/torch_sparse/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/work/mtgraovac_lab/rahit/test/.pixi/envs/default/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/work/mtgraovac_lab/rahit/test/.pixi/envs/default/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /work/mtgraovac_lab/rahit/test/.pixi/envs/default/lib/python3.10/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
```

**Comment by rahit** [comment]
Okay. After specifying `torch` wheel, following setup seems to work for me:


```toml
[workspace]
name = "test-env"
version = "0.1.0"
channels = ["nvidia", "pytorch", "conda-forge"]
platforms = ["linux-64"]

[system-requirements]
cuda = "12.1"

[tasks]
test_env = { cmd = "python test_env.py" }

[dependencies]
python = "3.10.*"
cuda-version = "12.1.*"
pytorch-cuda = {version = "12.1.*", channel = "pytorch"}

[pypi-dependencies]
torch = { url = "https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=0d4e8c52a1fcf5ed6cfc256d9a370fcf4360958fc79d0b08a51d55e70914df46" }
torch_scatter = { url = "https://data.pyg.org/whl/torch-2.1.0%2Bcu121/torch_scatter-2.1.2%2Bpt21cu121-cp310-cp310-linux_x86_64.whl" }
torch_sparse = { url = "https://data.pyg.org/whl/torch-2.1.0%2Bcu121/torch_sparse-0.6.18%2Bpt21cu121-cp310-cp310-linux_x86_64.whl" }


```
